pub fn print_logo() {
    println!(
        r#"
        ....................................................................................................
        ..................................',:clodxxkkOOOO00000OOOkxxdlc:,'..................................
        .............................,cdk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0Oxoc,............................
        ..........................'lOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOl'.........................
        .........................lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c........................
        ........................oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.......................
        .......................:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;......................
        .......................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd......................
        ......................;KMMMMWNKOkxxxkOKNWMMMMMMMMMMMMMMMMMMWNKOxddddxOKWMMMMMO,.....................
        ......................lNMMNOdlllc:;,...,cd0NMMMMMMMMMMMMW0dc,...',;;:ccokXMMMK:.....................
        ......................xWMXxdOXWWKOdl::;,...:kNMMMMMMMMWOc....;::;:co0NNKOkKWMNl.....................
        .....................,OMWXXWMMMMMWX0dc;;;,...oNMMMMMMM0;..,:c::lx0KNWMMMMNXWMWd.....................
        .....................:KMMMMMMMMMMMMMMW0l,';;;dNMMMMMMMKocol:cxXWMMMMMMMMMMMMMMk. ...................
        .....................cNMMMMMMMMMMMMMMMMWKl',oXMMMMMMMMWXdclONMMMMMMMMMMMMMMMMMO' ...................
        .....................oNMMMMMWNKOkxxkOKNWMWk,.cKMMMMMMMKol0WMMNKOxddxk0XWMMMMMM0, ...................
        .....................dWMMMWOl,........;lkXWx..oNMMMMMMNKNMNOo;........':xXMMMM0,....................
        .....................dWW0xc..... ........;0O, :KMMMMMMMMMKc.. ...........:kKXW0; ...................
        .....................dWWx,.';:ccccccccllokXO, ;0MMMMMMMMMNOdooddxxxxdddxkO0KXN0,....................
        .....................oWW0O0XNWWMMMMMWMMMMMMO, ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0, ...................
        .....................cXMMMMMMMMMMMMMMMMMMMMk' ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,....................
        ......................xWMMMMMMMMMMMMMMMMMMNo..;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk' ...................
        ......................,kWMMMMMMMMMMMMMMMMM0,. ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK:.....................
        ......................,:lONMMMMMMMMMMMMMWO;...:KMMMMMMMMWWMMMMMMMMMMMMMMMMMNO;......................
        ......................ck:.:dOKXXXXK00XXx:.....lNMMMMMMMN0k0NMMWWWWWMMMWWN0xxo'......................
        .......................d0:.;,'lO0OOOKXx..;xc..xWMMMMMMMMWXk0WMWKkkxxdl:cc',Ox'......................
        .......................'k0lod,'dNMMMMMKc,kXc.,0MMMMMMMMMMMNNMMMMWWNKl.'xd;xK:.......................
        ........................,OKodd,.;kXWMMMNKNXo.:KMMMMMMMMMMMMMMMMMMW0:.,OKldKo........................
        .........................;OXxdd;..,lx0XWMMW0:,d0XNNN0do0WMMMMMWXOl..;kkcdKx.........................
        ..........................,OXkloo;....,:ll:'....cll;...'lkOOxoc,...lxl,oXx'.........................
        ...........................,kNOccdxdc,... .....lKXKk;........ ..,lxo,'xXx'..........................
        ............................'kNKc.;xKX0kdl:;;cd0K000k:....';:lx0NNO::OXo............................
        .............................'xNXo..,oOXWMWWWNXK00OOOOOO0KXNWMMMMXddKXl.............................
        ...............................oNNo. .oO00KXNNWWNNNNWMMMMMMMMMMWKdkN0:..............................
        ................................oXNd.'OMWXK00kl;;,,,:dXMMMMMMMWOo0NO;...............................
        .................................cKNo;OMMMMMMWk' ...'dNMMMMMMNkdKNd'................................
        ..................................;OXkOWMMMMMMO,....:XMMMMMMMX0XXl..................................
        ...................................'dXWWMMMMMXc.....'kWMMMMMMMW0:...................................
        .....................................:0WMMMMMk' .....cXMMMMMMNx'....................................
        ......................................'dXMMMMO,......lNMMMMW0c......................................
        ........................................:OWMMXc.....'kMMMWKo'.......................................
        ..........................................cONWk' ...cXMW0o,.........................................
        ............................................;ll'....;do:............................................
    "#
    );
}
